name: Docker Build Only

on:
  push:
    branches:
      - '**'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend container
        run: docker compose -f docker/docker-compose.yml build backend

      - name: Build db container
        run: docker compose -f docker/docker-compose.yml build db

      - name: Build nginx container
        run: docker compose -f docker/docker-compose.yml build nginx
